services:
  opus-web:
    container_name: opus-web
    image: opus-web:latest
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      UPDATE_DB: "${UPDATE_DB:-0}"
    volumes:
      - ./data/opus:/data/opus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]

